### ISSUE TITLE
Does not render properly in iOS 11

### ISSUE THREAD

**Issue by edwardsanchez** [asavihay/PBROrbs-iOS10-SceneKit#5]
<img width="427" alt="screen shot 2018-03-30 at 10 50 05 pm" src="https://user-images.githubusercontent.com/40975/38160106-b6ed5828-346c-11e8-8fa1-b10ad4c9a2b1.png">

**Comment by stevenyix** [comment]
@edwardsanchez are you running this on a physical device?  requires the Metal renderer, the simulator uses the opengl renderer.  when i ran this on a simulator i got the same result you did; when i ran it on an iphone 6s it rendered properly.

**Comment by edwardsanchez** [comment]
Yes, you're correct. Running on device works fine. Thanks and sorry for the false alarm! Great example and blog! Thanks!
